### ISSUE TITLE
Netstandard dotnet52 support for Client and Core

### ISSUE THREAD

**Issue by juanfranblanco** [Gekctek/JsonRpc.Router#12]
Hi, will it be possible to target at least the netstandard dotnet52 which is 1.1 to allow support the greatest number of platforms.

More info: http://dotnet.github.io/docs/libraries/libraries-with-cli.html

**Comment by Gekctek** [comment]
I will be able to change the client and core to use these but not the router itself. It doesn't sound like that is an issue to you though. Lowest I can change the router to is dotnet54 right now

**Comment by juanfranblanco** [comment]
Many thanks +1
